In [13]:
import os
import pandas as pd

folder = 'balance_sheet'
balance_sheets = {}
errors = {}

if not os.path.isdir(folder):
    print(f"Directory not found: {folder}")
else:
    files = sorted([f for f in os.listdir(folder) if f.lower().endswith('.csv')])
    if not files:
        print(f"No CSV files found in {folder}")
    else:
        for fname in files:
            path = os.path.join(folder, fname)
            try:
                df_bs = pd.read_csv(path)
                sector = df_bs["sector"][0]
                industry = df_bs["industry"][0]
                Shares_Outstanding = df_bs["Shares Outstanding"][0]
                Current_Price = df_bs["Current Price"][0]
                df_bs = df_bs.drop("Shares Outstanding", axis=1)
                df_bs = df_bs.drop("Current Price", axis=1)
                df_bs = df_bs.drop("sector", axis=1)
                df_bs = df_bs.drop("industry", axis=1)
                df_bs = df_bs.T
                df_col = df_bs.iloc[0]
                df_bs.columns = df_col
                df_bs = df_bs[1:].reset_index()
                
                df_bs = df_bs.rename(columns={'index': 'date'}) 
                df_bs['sector'] = sector
                df_bs['industry'] = industry
                df_bs['Shares Outstanding'] = Shares_Outstanding
                df_bs['Current Price'] = Current_Price
                balance_sheets[fname] = df_bs
                print(f"Loaded {fname} -> shape: {df_bs.shape}")
            except Exception as e:
                errors[fname] = str(e)
                print(f"Failed to load {fname}: {e}")

if errors:
    print("Errors for some files:")
    for f, err in errors.items():
        print(f, ":", err)

Loaded 360ONE.NS.csv -> shape: (5, 81)
Loaded 3MINDIA.NS.csv -> shape: (4, 77)
Loaded AADHARHFC.NS.csv -> shape: (5, 69)
Loaded AARTIIND.NS.csv -> shape: (5, 89)
Loaded AAVAS.NS.csv -> shape: (5, 77)
Loaded ABB.NS.csv -> shape: (5, 84)
Loaded ABBOTINDIA.NS.csv -> shape: (4, 76)
Loaded ABCAPITAL.NS.csv -> shape: (5, 69)
Loaded ABFRL.NS.csv -> shape: (5, 93)
Loaded ABREL.NS.csv -> shape: (4, 91)
Loaded ABSLAMC.NS.csv -> shape: (5, 71)
Loaded ACC.NS.csv -> shape: (5, 86)
Loaded ACE.NS.csv -> shape: (5, 89)
Loaded ACMESOLAR.NS.csv -> shape: (4, 86)
Loaded ADANIENSOL.NS.csv -> shape: (5, 84)
Loaded ADANIENT.NS.csv -> shape: (5, 93)
Loaded ADANIGREEN.NS.csv -> shape: (5, 91)
Loaded ADANIPORTS.NS.csv -> shape: (5, 98)
Loaded ADANIPOWER.NS.csv -> shape: (5, 89)
Loaded ADVENTHTL.NS.csv -> shape: (2, 40)
Loaded AEGISLOG.NS.csv -> shape: (5, 85)
Loaded AEGISVOPAK.NS.csv -> shape: (3, 77)
Loaded AFCONS.NS.csv -> shape: (5, 85)
Loaded AFFLE.NS.csv -> shape: (5, 83)
Loaded AGARWALEYE.NS.csv -> shape: (4, 86)
Loaded AIAENG.NS.csv -> shape: (5, 84)
Loaded AIIL.NS.csv -> shape: (5, 78)
Loaded AJANTPHARM.NS.csv -> shape: (5, 92)
Loaded AKUMS.NS.csv -> shape: (5, 89)
Loaded AKZOINDIA.NS.csv -> shape: (5, 80)
Loaded ALKEM.NS.csv -> shape: (5, 88)
Loaded ALKYLAMINE.NS.csv -> shape: (5, 84)
Loaded ALOKINDS.NS.csv -> shape: (5, 85)
Loaded AMBER.NS.csv -> shape: (5, 91)
Loaded AMBUJACEM.NS.csv -> shape: (4, 88)
Loaded ANANDRATHI.NS.csv -> shape: (5, 75)
Loaded ANANTRAJ.NS.csv -> shape: (5, 84)
Loaded ANGELONE.NS.csv -> shape: (5, 77)
Loaded APARINDS.NS.csv -> shape: (5, 86)
Loaded APLAPOLLO.NS.csv -> shape: (5, 89)
Loaded APLLTD.NS.csv -> shape: (5, 87)
Loaded APOLLOHOSP.NS.csv -> shape: (5, 92)
Loaded APOLLOTYRE.NS.csv -> shape: (5, 93)
Loaded APTUS.NS.csv -> shape: (5, 50)
Loaded ARE&M.NS.csv -> shape: (4, 80)
Loaded ASAHIINDIA.NS.csv -> shape: (5, 86)
Loaded ASHOKLEY.NS.csv -> shape: (5, 97)
Loaded ASIANPAINT.NS.csv -> shape: (5, 96)
Loaded ASTERDM.NS.csv -> shape: (5, 88)
Loaded ASTRAL.NS.csv -> shape: (5, 88)
Loaded ASTRAZEN.NS.csv -> shape: (5, 76)
Loaded ATGL.NS.csv -> shape: (5, 83)
Loaded ATHERENERG.NS.csv -> shape: (3, 73)
Loaded ATUL.NS.csv -> shape: (5, 94)
Loaded AUBANK.NS.csv -> shape: (5, 44)
Loaded AUROPHARMA.NS.csv -> shape: (5, 96)
Loaded AWL.NS.csv -> shape: (5, 89)
Loaded AXISBANK.NS.csv -> shape: (5, 52)
Loaded BAJAJ-AUTO.NS.csv -> shape: (5, 91)
Loaded BAJAJFINSV.NS.csv -> shape: (5, 68)
Loaded BAJAJHFL.NS.csv -> shape: (4, 68)
Loaded BAJAJHLDNG.NS.csv -> shape: (5, 45)
Loaded BAJFINANCE.NS.csv -> shape: (4, 55)
Loaded BALKRISIND.NS.csv -> shape: (5, 84)
Loaded BALRAMCHIN.NS.csv -> shape: (5, 82)
Loaded BANDHANBNK.NS.csv -> shape: (4, 44)
Loaded BANKBARODA.NS.csv -> shape: (4, 47)
Loaded BANKINDIA.NS.csv -> shape: (5, 46)
Loaded BASF.NS.csv -> shape: (5, 85)
Loaded BATAINDIA.NS.csv -> shape: (5, 77)
Loaded BAYERCROP.NS.csv -> shape: (5, 79)
Loaded BBTC.NS.csv -> shape: (5, 93)
Loaded BDL.NS.csv -> shape: (5, 84)
Loaded BEL.NS.csv -> shape: (5, 85)
Loaded BEML.NS.csv -> shape: (5, 88)
Loaded BERGEPAINT.NS.csv -> shape: (5, 86)
Loaded BHARATFORG.NS.csv -> shape: (5, 97)
Loaded BHARTIARTL.NS.csv -> shape: (5, 95)
Loaded BHARTIHEXA.NS.csv -> shape: (5, 81)
Loaded BHEL.NS.csv -> shape: (5, 86)
Loaded BIKAJI.NS.csv -> shape: (4, 86)
Loaded BIOCON.NS.csv -> shape: (5, 94)
Loaded BLS.NS.csv -> shape: (5, 86)
Loaded BLUEDART.NS.csv -> shape: (5, 80)
Loaded BLUEJET.NS.csv -> shape: (5, 82)
Loaded BLUESTARCO.NS.csv -> shape: (5, 86)
Loaded BOSCHLTD.NS.csv -> shape: (5, 90)
Loaded BPCL.NS.csv -> shape: (5, 93)
Loaded BRIGADE.NS.csv -> shape: (5, 91)
Loaded BRITANNIA.NS.csv -> shape: (5, 89)
Loaded BSE.NS.csv -> shape: (5, 89)
Loaded BSOFT.NS.csv -> shape: (5, 82)
Loaded CAMPUS.NS.csv -> shape: (5, 82)
Loaded CAMS.NS.csv -> shape: (5, 77)
Loaded CANBK.NS.csv -> shape: (5, 43)
Loaded CANFINHOME.NS.csv -> shape: (5, 50)
Loaded CAPLIPOINT.NS.csv -> shape: (5, 87)
Loaded CARBORUNIV.NS.csv -> shape: (5, 89)
Loaded CASTROLIND.NS.csv -> shape: (5, 77)
Loaded CCL.NS.csv -> shape: (5, 82)
Loaded CDSL.NS.csv -> shape: (5, 78)
Loaded CEATLTD.NS.csv -> shape: (5, 92)
Loaded CENTRALBK.NS.csv -> shape: (5, 46)
Loaded CENTURYPLY.NS.csv -> shape: (5, 88)
Loaded CERA.NS.csv -> shape: (5, 92)
Loaded CESC.NS.csv -> shape: (5, 86)
Loaded CGCL.NS.csv -> shape: (5, 82)
Loaded CGPOWER.NS.csv -> shape: (5, 89)
Loaded CHALET.NS.csv -> shape: (5, 88)
Loaded CHAMBLFERT.NS.csv -> shape: (5, 90)
Loaded CHENNPETRO.NS.csv -> shape: (5, 87)
Loaded CHOICEIN.NS.csv -> shape: (5, 84)
Loaded CHOLAFIN.NS.csv -> shape: (5, 54)
Loaded CHOLAHLDNG.NS.csv -> shape: (5, 86)
Loaded CIPLA.NS.csv -> shape: (5, 93)
Loaded CLEAN.NS.csv -> shape: (5, 82)
Loaded COALINDIA.NS.csv -> shape: (5, 88)
Loaded COCHINSHIP.NS.csv -> shape: (5, 84)
Loaded COFORGE.NS.csv -> shape: (5, 87)
Loaded COHANCE.NS.csv -> shape: (5, 90)
Loaded COLPAL.NS.csv -> shape: (5, 78)
Loaded CONCOR.NS.csv -> shape: (5, 84)
Loaded CONCORDBIO.NS.csv -> shape: (5, 83)
Loaded COROMANDEL.NS.csv -> shape: (5, 86)
Loaded CRAFTSMAN.NS.csv -> shape: (5, 87)
Loaded CREDITACC.NS.csv -> shape: (5, 78)
Loaded CRISIL.NS.csv -> shape: (5, 76)
Loaded CROMPTON.NS.csv -> shape: (5, 86)
Loaded CUB.NS.csv -> shape: (5, 41)
Loaded CUMMINSIND.NS.csv -> shape: (5, 85)
Loaded CYIENT.NS.csv -> shape: (5, 90)
Loaded DABUR.NS.csv -> shape: (5, 90)
Loaded DALBHARAT.NS.csv -> shape: (5, 93)
Loaded DATAPATTNS.NS.csv -> shape: (5, 82)
Loaded DBREALTY.NS.csv -> shape: (5, 89)
Loaded DCMSHRIRAM.NS.csv -> shape: (5, 93)
Loaded DEEPAKFERT.NS.csv -> shape: (5, 88)
Loaded DEEPAKNTR.NS.csv -> shape: (5, 88)
Loaded DELHIVERY.NS.csv -> shape: (5, 84)
Loaded DEVYANI.NS.csv -> shape: (5, 85)
Loaded DIVISLAB.NS.csv -> shape: (5, 81)
Loaded DIXON.NS.csv -> shape: (5, 89)
Loaded DLF.NS.csv -> shape: (5, 94)
Loaded DMART.NS.csv -> shape: (5, 77)
Loaded DOMS.NS.csv -> shape: (5, 82)
Loaded DRREDDY.NS.csv -> shape: (5, 98)
Loaded ECLERX.NS.csv -> shape: (5, 84)
Loaded EICHERMOT.NS.csv -> shape: (5, 86)
Loaded EIDPARRY.NS.csv -> shape: (5, 94)
Loaded EIHOTEL.NS.csv -> shape: (5, 89)
Loaded ELECON.NS.csv -> shape: (5, 87)
Loaded ELGIEQUIP.NS.csv -> shape: (5, 87)
Loaded EMAMILTD.NS.csv -> shape: (5, 92)
Loaded EMCURE.NS.csv -> shape: (5, 82)
Loaded ENDURANCE.NS.csv -> shape: (5, 93)
Loaded ENGINERSIN.NS.csv -> shape: (5, 84)
Loaded ENRIN.NS.csv -> shape: (1, 55)
Loaded ERIS.NS.csv -> shape: (5, 87)
Loaded ESCORTS.NS.csv -> shape: (5, 89)
Loaded ETERNAL.NS.csv -> shape: (5, 85)
Loaded EXIDEIND.NS.csv -> shape: (5, 88)
Loaded FACT.NS.csv -> shape: (5, 87)
Loaded FEDERALBNK.NS.csv -> shape: (5, 53)
Loaded FINCABLES.NS.csv -> shape: (5, 82)
Loaded FINPIPE.NS.csv -> shape: (5, 87)
Loaded FIRSTCRY.NS.csv -> shape: (5, 86)
Loaded FIVESTAR.NS.csv -> shape: (5, 69)
Loaded FLUOROCHEM.NS.csv -> shape: (5, 88)
Loaded FORCEMOT.NS.csv -> shape: (5, 80)
Loaded FORTIS.NS.csv -> shape: (5, 93)
Loaded FSL.NS.csv -> shape: (5, 87)
Loaded GAIL.NS.csv -> shape: (5, 83)
Loaded GESHIP.NS.csv -> shape: (5, 82)
Loaded GICRE.NS.csv -> shape: (4, 59)
Loaded GILLETTE.NS.csv -> shape: (4, 71)
Loaded GLAND.NS.csv -> shape: (5, 83)
Loaded GLAXO.NS.csv -> shape: (5, 78)
Loaded GLENMARK.NS.csv -> shape: (5, 83)
Loaded GMDCLTD.NS.csv -> shape: (5, 87)
Loaded GMRAIRPORT.NS.csv -> shape: (5, 98)
Loaded GODFRYPHLP.NS.csv -> shape: (5, 87)
Loaded GODIGIT.NS.csv -> shape: (5, 60)
Loaded GODREJAGRO.NS.csv -> shape: (5, 88)
Loaded GODREJCP.NS.csv -> shape: (5, 91)
Loaded GODREJIND.NS.csv -> shape: (5, 92)
Loaded GODREJPROP.NS.csv -> shape: (5, 92)
Loaded GPIL.NS.csv -> shape: (5, 89)
Loaded GRANULES.NS.csv -> shape: (5, 89)
Loaded GRAPHITE.NS.csv -> shape: (5, 89)
Loaded GRASIM.NS.csv -> shape: (5, 102)
Loaded GRAVITA.NS.csv -> shape: (5, 90)
Loaded GRSE.NS.csv -> shape: (5, 80)
Loaded GSPL.NS.csv -> shape: (5, 87)
Loaded GUJGASLTD.NS.csv -> shape: (5, 83)
Loaded GVT&D.NS.csv -> shape: (5, 78)
Loaded HAL.NS.csv -> shape: (4, 91)
Loaded HAPPSTMNDS.NS.csv -> shape: (5, 80)
Loaded HAVELLS.NS.csv -> shape: (5, 86)
Loaded HBLENGINE.NS.csv -> shape: (5, 89)
Loaded HCLTECH.NS.csv -> shape: (5, 92)
Loaded HDFCAMC.NS.csv -> shape: (5, 68)
Loaded HDFCBANK.NS.csv -> shape: (5, 64)
Loaded HDFCLIFE.NS.csv -> shape: (5, 64)
Loaded HEG.NS.csv -> shape: (5, 91)
Loaded HEROMOTOCO.NS.csv -> shape: (5, 85)
Loaded HEXT.NS.csv -> shape: (5, 82)
Loaded HFCL.NS.csv -> shape: (5, 87)
Loaded HINDALCO.NS.csv -> shape: (5, 96)
Loaded HINDCOPPER.NS.csv -> shape: (5, 85)
Loaded HINDPETRO.NS.csv -> shape: (5, 87)
Loaded HINDUNILVR.NS.csv -> shape: (4, 87)
Loaded HINDZINC.NS.csv -> shape: (5, 84)
Loaded HOMEFIRST.NS.csv -> shape: (5, 67)
Loaded HONASA.NS.csv -> shape: (5, 77)
Loaded HONAUT.NS.csv -> shape: (5, 76)
Loaded HSCL.NS.csv -> shape: (5, 80)
Loaded HUDCO.NS.csv -> shape: (5, 55)
Loaded HYUNDAI.NS.csv -> shape: (5, 77)
Loaded ICICIBANK.NS.csv -> shape: (5, 56)
Loaded ICICIGI.NS.csv -> shape: (5, 62)
Loaded ICICIPRULI.NS.csv -> shape: (5, 62)
Loaded IDBI.NS.csv -> shape: (4, 48)
Loaded IDEA.NS.csv -> shape: (5, 93)
Loaded IDFCFIRSTB.NS.csv -> shape: (4, 49)
Loaded IEX.NS.csv -> shape: (5, 78)
Loaded IFCI.NS.csv -> shape: (5, 59)
Loaded IGIL.NS.csv -> shape: (4, 75)
Loaded IGL.NS.csv -> shape: (5, 80)
Loaded IIFL.NS.csv -> shape: (5, 55)
Loaded IKS.NS.csv -> shape: (4, 82)
Loaded INDGN.NS.csv -> shape: (5, 77)
Loaded INDHOTEL.NS.csv -> shape: (5, 87)
Loaded INDIACEM.NS.csv -> shape: (5, 90)
Loaded INDIAMART.NS.csv -> shape: (5, 80)
Loaded INDIANB.NS.csv -> shape: (4, 44)
Loaded INDIGO.NS.csv -> shape: (5, 89)
Loaded INDUSINDBK.NS.csv -> shape: (5, 47)
Loaded INDUSTOWER.NS.csv -> shape: (5, 84)
Loaded INFY.NS.csv -> shape: (5, 96)
Loaded INOXINDIA.NS.csv -> shape: (5, 85)
Loaded INOXWIND.NS.csv -> shape: (5, 86)
Loaded INTELLECT.NS.csv -> shape: (5, 84)
Loaded IOB.NS.csv -> shape: (4, 46)
Loaded IOC.NS.csv -> shape: (5, 97)
Loaded IPCALAB.NS.csv -> shape: (4, 93)
Loaded IRB.NS.csv -> shape: (5, 89)
Loaded IRCON.NS.csv -> shape: (5, 87)
Loaded IRCTC.NS.csv -> shape: (5, 80)
Loaded IREDA.NS.csv -> shape: (5, 79)
Loaded IRFC.NS.csv -> shape: (5, 68)
Loaded ITC.NS.csv -> shape: (5, 86)
Loaded ITCHOTELS.NS.csv -> shape: (2, 82)
Loaded ITI.NS.csv -> shape: (5, 85)
Loaded J&KBANK.NS.csv -> shape: (5, 49)
Loaded JBCHEPHARM.NS.csv -> shape: (5, 88)
Loaded JBMA.NS.csv -> shape: (5, 88)
Loaded JINDALSAW.NS.csv -> shape: (5, 93)
Loaded JINDALSTEL.NS.csv -> shape: (5, 93)
Loaded JIOFIN.NS.csv -> shape: (5, 74)
Loaded JKCEMENT.NS.csv -> shape: (5, 90)
Loaded JKTYRE.NS.csv -> shape: (4, 90)
Loaded JMFINANCIL.NS.csv -> shape: (5, 46)
Loaded JPPOWER.NS.csv -> shape: (5, 90)
Loaded JSL.NS.csv -> shape: (5, 94)
Loaded JSWENERGY.NS.csv -> shape: (5, 93)
Loaded JSWINFRA.NS.csv -> shape: (5, 88)
Loaded JSWSTEEL.NS.csv -> shape: (5, 93)
Loaded JUBLFOOD.NS.csv -> shape: (5, 90)
Loaded JUBLINGREA.NS.csv -> shape: (5, 87)
Loaded JUBLPHARMA.NS.csv -> shape: (5, 88)
Loaded JWL.NS.csv -> shape: (5, 89)
Loaded JYOTHYLAB.NS.csv -> shape: (5, 85)
Loaded JYOTICNC.NS.csv -> shape: (5, 80)
Loaded KAJARIACER.NS.csv -> shape: (5, 88)
Loaded KALYANKJIL.NS.csv -> shape: (5, 87)
Loaded KARURVYSYA.NS.csv -> shape: (5, 42)
Loaded KAYNES.NS.csv -> shape: (5, 82)
Loaded KEC.NS.csv -> shape: (5, 84)
Loaded KEI.NS.csv -> shape: (5, 87)
Loaded KFINTECH.NS.csv -> shape: (5, 83)
Loaded KIMS.NS.csv -> shape: (5, 84)
Loaded KIRLOSBROS.NS.csv -> shape: (5, 86)
Loaded KIRLOSENG.NS.csv -> shape: (5, 93)
Loaded KOTAKBANK.NS.csv -> shape: (5, 52)
Loaded KPIL.NS.csv -> shape: (5, 92)
Loaded KPITTECH.NS.csv -> shape: (5, 86)
Loaded KPRMILL.NS.csv -> shape: (5, 78)
Loaded KSB.NS.csv -> shape: (5, 80)
Loaded LALPATHLAB.NS.csv -> shape: (5, 80)
Loaded LATENTVIEW.NS.csv -> shape: (5, 80)
Loaded LAURUSLABS.NS.csv -> shape: (5, 89)
Loaded LEMONTREE.NS.csv -> shape: (5, 80)
Loaded LICHSGFIN.NS.csv -> shape: (5, 56)
Loaded LICI.NS.csv -> shape: (5, 61)
Loaded LINDEINDIA.NS.csv -> shape: (5, 86)
Loaded LLOYDSME.NS.csv -> shape: (5, 82)
Loaded LODHA.NS.csv -> shape: (5, 89)
Loaded LT.NS.csv -> shape: (5, 90)
Loaded LTF.NS.csv -> shape: (5, 54)
Loaded LTFOODS.NS.csv -> shape: (5, 90)
Loaded LTIM.NS.csv -> shape: (5, 87)
Loaded LTTS.NS.csv -> shape: (5, 81)
Loaded LUPIN.NS.csv -> shape: (5, 90)
Loaded M&M.NS.csv -> shape: (5, 96)
Loaded M&MFIN.NS.csv -> shape: (5, 57)
Loaded MAHABANK.NS.csv -> shape: (5, 47)
Loaded MAHSCOOTER.NS.csv -> shape: (5, 71)
Loaded MAHSEAMLES.NS.csv -> shape: (5, 86)
Loaded MANAPPURAM.NS.csv -> shape: (5, 52)
Loaded MANKIND.NS.csv -> shape: (5, 88)
Loaded MANYAVAR.NS.csv -> shape: (5, 83)
Loaded MAPMYINDIA.NS.csv -> shape: (5, 87)
Loaded MARICO.NS.csv -> shape: (5, 91)
Loaded MARUTI.NS.csv -> shape: (5, 88)
Loaded MAXHEALTH.NS.csv -> shape: (5, 84)
Loaded MAZDOCK.NS.csv -> shape: (4, 79)
Loaded MCX.NS.csv -> shape: (5, 78)
Loaded MEDANTA.NS.csv -> shape: (5, 84)
Loaded METROPOLIS.NS.csv -> shape: (5, 84)
Loaded MFSL.NS.csv -> shape: (5, 66)
Loaded MGL.NS.csv -> shape: (5, 75)
Loaded MINDACORP.NS.csv -> shape: (5, 89)
Loaded MMTC.NS.csv -> shape: (5, 82)
Loaded MOTHERSON.NS.csv -> shape: (5, 89)
Loaded MOTILALOFS.NS.csv -> shape: (5, 76)
Loaded MPHASIS.NS.csv -> shape: (5, 88)
Loaded MRF.NS.csv -> shape: (4, 85)
Loaded MRPL.NS.csv -> shape: (5, 86)
Loaded MSUMI.NS.csv -> shape: (5, 75)
Loaded MUTHOOTFIN.NS.csv -> shape: (4, 54)
Loaded NAM-INDIA.NS.csv -> shape: (5, 76)
Loaded NATCOPHARM.NS.csv -> shape: (5, 85)
Loaded NATIONALUM.NS.csv -> shape: (5, 85)
Loaded NAUKRI.NS.csv -> shape: (5, 89)
Loaded NAVA.NS.csv -> shape: (5, 89)
Loaded NAVINFLUOR.NS.csv -> shape: (5, 89)
Loaded NBCC.NS.csv -> shape: (5, 85)
Loaded NCC.NS.csv -> shape: (5, 83)
Loaded NESTLEIND.NS.csv -> shape: (4, 85)
Loaded NETWEB.NS.csv -> shape: (5, 82)
Loaded NEULANDLAB.NS.csv -> shape: (5, 85)
Loaded NEWGEN.NS.csv -> shape: (5, 81)
Loaded NH.NS.csv -> shape: (5, 91)
Loaded NHPC.NS.csv -> shape: (5, 91)
Loaded NIACL.NS.csv -> shape: (4, 53)
Loaded NIVABUPA.NS.csv -> shape: (4, 59)
Loaded NLCINDIA.NS.csv -> shape: (5, 84)
Loaded NMDC.NS.csv -> shape: (4, 86)
Loaded NSLNISP.NS.csv -> shape: (5, 80)
Loaded NTPC.NS.csv -> shape: (4, 91)
Loaded NTPCGREEN.NS.csv -> shape: (3, 78)
Loaded NUVAMA.NS.csv -> shape: (3, 75)
Loaded NUVOCO.NS.csv -> shape: (5, 86)
Loaded NYKAA.NS.csv -> shape: (5, 85)
Loaded OBEROIRLTY.NS.csv -> shape: (5, 84)
Loaded OFSS.NS.csv -> shape: (4, 80)
Loaded OIL.NS.csv -> shape: (5, 94)
Loaded OLAELEC.NS.csv -> shape: (5, 82)
Loaded OLECTRA.NS.csv -> shape: (5, 78)
Loaded ONESOURCE.NS.csv -> shape: (3, 83)
Loaded ONGC.NS.csv -> shape: (5, 97)
Loaded PAGEIND.NS.csv -> shape: (5, 81)
Loaded PATANJALI.NS.csv -> shape: (5, 89)
Loaded PAYTM.NS.csv -> shape: (5, 84)
Loaded PCBL.NS.csv -> shape: (5, 85)
Loaded PERSISTENT.NS.csv -> shape: (5, 87)
Loaded PETRONET.NS.csv -> shape: (5, 77)
Loaded PFC.NS.csv -> shape: (5, 56)
Loaded PFIZER.NS.csv -> shape: (5, 82)
Loaded PGEL.NS.csv -> shape: (5, 90)
Loaded PGHH.NS.csv -> shape: (4, 74)
Loaded PHOENIXLTD.NS.csv -> shape: (5, 94)
Loaded PIDILITIND.NS.csv -> shape: (5, 90)
Loaded PIIND.NS.csv -> shape: (5, 92)
Loaded PNB.NS.csv -> shape: (5, 46)
Loaded PNBHOUSING.NS.csv -> shape: (5, 55)
Loaded POLICYBZR.NS.csv -> shape: (5, 78)
Loaded POLYCAB.NS.csv -> shape: (5, 88)
Loaded POLYMED.NS.csv -> shape: (5, 89)
Loaded POONAWALLA.NS.csv -> shape: (5, 89)
Loaded POWERGRID.NS.csv -> shape: (5, 87)
Loaded POWERINDIA.NS.csv -> shape: (5, 81)
Loaded PPLPHARMA.NS.csv -> shape: (5, 90)
Loaded PRAJIND.NS.csv -> shape: (5, 85)
Loaded PREMIERENE.NS.csv -> shape: (5, 91)
Loaded PRESTIGE.NS.csv -> shape: (5, 88)
Loaded PTCIL.NS.csv -> shape: (5, 80)
Loaded PVRINOX.NS.csv -> shape: (5, 83)
Loaded RADICO.NS.csv -> shape: (5, 88)
Loaded RAILTEL.NS.csv -> shape: (5, 81)
Loaded RAINBOW.NS.csv -> shape: (5, 81)
Loaded RAMCOCEM.NS.csv -> shape: (5, 87)
Loaded RBLBANK.NS.csv -> shape: (5, 49)
Loaded RCF.NS.csv -> shape: (5, 91)
Loaded RECLTD.NS.csv -> shape: (5, 53)
Loaded REDINGTON.NS.csv -> shape: (5, 83)
Loaded RELIANCE.NS.csv -> shape: (5, 82)
Loaded RELINFRA.NS.csv -> shape: (5, 93)
Loaded RHIM.NS.csv -> shape: (5, 85)
Loaded RITES.NS.csv -> shape: (5, 84)
Loaded RKFORGE.NS.csv -> shape: (5, 89)
Loaded RPOWER.NS.csv -> shape: (5, 88)
Loaded RRKABEL.NS.csv -> shape: (5, 89)
Loaded RVNL.NS.csv -> shape: (5, 82)
Loaded SAGILITY.NS.csv -> shape: (4, 74)
Loaded SAIL.NS.csv -> shape: (5, 90)
Loaded SAILIFE.NS.csv -> shape: (4, 84)
Loaded SAMMAANCAP.NS.csv -> shape: (5, 63)
Loaded SAPPHIRE.NS.csv -> shape: (5, 79)
Loaded SARDAEN.NS.csv -> shape: (5, 84)
Loaded SAREGAMA.NS.csv -> shape: (5, 85)
Loaded SBFC.NS.csv -> shape: (5, 74)
Loaded SBICARD.NS.csv -> shape: (5, 47)
Loaded SBILIFE.NS.csv -> shape: (4, 54)
Loaded SBIN.NS.csv -> shape: (4, 49)
Loaded SCHAEFFLER.NS.csv -> shape: (5, 81)
Loaded SCHNEIDER.NS.csv -> shape: (5, 76)
Loaded SCI.NS.csv -> shape: (5, 82)
Loaded SHREECEM.NS.csv -> shape: (5, 91)
Loaded SHRIRAMFIN.NS.csv -> shape: (4, 55)
Loaded SHYAMMETL.NS.csv -> shape: (5, 94)
Loaded SIEMENS.NS.csv -> shape: (5, 90)
Loaded SIGNATURE.NS.csv -> shape: (5, 88)
Loaded SJVN.NS.csv -> shape: (5, 83)
Loaded SKFINDIA.NS.csv -> shape: (5, 81)
Loaded SOBHA.NS.csv -> shape: (5, 88)
Loaded SOLARINDS.NS.csv -> shape: (5, 91)
Loaded SONACOMS.NS.csv -> shape: (5, 84)
Loaded SONATSOFTW.NS.csv -> shape: (5, 82)
Loaded SRF.NS.csv -> shape: (5, 91)
Loaded STARHEALTH.NS.csv -> shape: (5, 58)
Loaded SUMICHEM.NS.csv -> shape: (5, 82)
Loaded SUNDARMFIN.NS.csv -> shape: (5, 56)
Loaded SUNDRMFAST.NS.csv -> shape: (5, 90)
Loaded SUNPHARMA.NS.csv -> shape: (5, 95)
Loaded SUNTV.NS.csv -> shape: (5, 79)
Loaded SUPREMEIND.NS.csv -> shape: (5, 87)
Loaded SUZLON.NS.csv -> shape: (5, 82)
Loaded SWANCORP.NS.csv -> shape: (5, 87)
Loaded SWIGGY.NS.csv -> shape: (4, 82)
Loaded SYNGENE.NS.csv -> shape: (5, 85)
Loaded SYRMA.NS.csv -> shape: (5, 89)
Loaded TARIL.NS.csv -> shape: (5, 91)
Loaded TATACHEM.NS.csv -> shape: (5, 91)
Loaded TATACOMM.NS.csv -> shape: (5, 90)
Loaded TATACONSUM.NS.csv -> shape: (5, 95)
Loaded TATAELXSI.NS.csv -> shape: (5, 78)
Loaded TATAINVEST.NS.csv -> shape: (4, 48)
Loaded TATAPOWER.NS.csv -> shape: (5, 95)
Loaded TATASTEEL.NS.csv -> shape: (5, 94)
Loaded TATATECH.NS.csv -> shape: (5, 78)
Loaded TBOTEK.NS.csv -> shape: (5, 82)
Loaded TCS.NS.csv -> shape: (5, 84)
Loaded TECHM.NS.csv -> shape: (5, 91)
Loaded TECHNOE.NS.csv -> shape: (5, 84)
Loaded TEJASNET.NS.csv -> shape: (5, 79)
Loaded THELEELA.NS.csv -> shape: (4, 81)
Loaded THERMAX.NS.csv -> shape: (4, 92)
Loaded TIINDIA.NS.csv -> shape: (5, 93)
Loaded TIMKEN.NS.csv -> shape: (5, 79)
Loaded TITAGARH.NS.csv -> shape: (5, 92)
Loaded TITAN.NS.csv -> shape: (5, 91)
Loaded TMPV.NS.csv -> shape: (5, 111)
Loaded TORNTPHARM.NS.csv -> shape: (5, 85)
Loaded TORNTPOWER.NS.csv -> shape: (5, 87)
Loaded TRENT.NS.csv -> shape: (5, 88)
Loaded TRIDENT.NS.csv -> shape: (5, 88)
Loaded TRITURBINE.NS.csv -> shape: (5, 86)
Loaded TRIVENI.NS.csv -> shape: (5, 94)
Loaded TTML.NS.csv -> shape: (5, 73)
Loaded TVSMOTOR.NS.csv -> shape: (5, 90)
Loaded UBL.NS.csv -> shape: (5, 84)
Loaded UCOBANK.NS.csv -> shape: (5, 44)
Loaded ULTRACEMCO.NS.csv -> shape: (5, 92)
Loaded UNIONBANK.NS.csv -> shape: (4, 50)
Loaded UNITDSPR.NS.csv -> shape: (5, 94)
Loaded UNOMINDA.NS.csv -> shape: (5, 90)
Loaded UPL.NS.csv -> shape: (5, 93)
Loaded USHAMART.NS.csv -> shape: (5, 91)
Loaded UTIAMC.NS.csv -> shape: (5, 65)
Loaded VBL.NS.csv -> shape: (5, 88)
Loaded VEDL.NS.csv -> shape: (5, 113)
Loaded VENTIVE.NS.csv -> shape: (4, 87)
Loaded VGUARD.NS.csv -> shape: (5, 90)
Loaded VIJAYA.NS.csv -> shape: (5, 78)
Loaded VMM.NS.csv -> shape: (4, 74)
Loaded VOLTAS.NS.csv -> shape: (4, 89)
Loaded VTL.NS.csv -> shape: (5, 91)
Loaded WAAREEENER.NS.csv -> shape: (5, 93)
Loaded WELCORP.NS.csv -> shape: (5, 94)
Loaded WELSPUNLIV.NS.csv -> shape: (5, 91)
Loaded WHIRLPOOL.NS.csv -> shape: (5, 83)
Loaded WIPRO.NS.csv -> shape: (5, 105)
Loaded WOCKPHARMA.NS.csv -> shape: (5, 85)
Loaded YESBANK.NS.csv -> shape: (5, 48)
Loaded ZEEL.NS.csv -> shape: (5, 89)
Loaded ZENSARTECH.NS.csv -> shape: (5, 82)
Loaded ZENTEC.NS.csv -> shape: (5, 88)
Loaded ZFCVINDIA.NS.csv -> shape: (5, 75)

In [ ]:
df_bs

Unnamed: 0,date,Treasury Shares Number,Ordinary Shares Number,Share Issued,Net Debt,Total Debt,Tangible Book Value,Invested Capital,Working Capital,Net Tangible Assets,...,Allowance For Doubtful Accounts Receivable,Gross Accounts Receivable,Cash Cash Equivalents And Short Term Investments,Other Short Term Investments,Cash And Cash Equivalents,Cash Financial,sector,industry,Shares Outstanding,Current Price
0,2025-03-31 00:00:00,NaN,1006233990.0,1006233990.0,23427000000.0,32132000000.0,154874000000.0,271226000000.0,80045000000.0,154874000000.0,...,-737000000.0,40984000000.0,78282000000.0,70014000000.0,8268000000.0,8268000000.0,Healthcare,Drug Manufacturers - Specialty & Generic,1006233990,929.15
1,2024-03-31 00:00:00,0.0,1006233990.0,1006233990.0,3556000000.0,8042000000.0,119525000000.0,205981000000.0,61595000000.0,119525000000.0,...,-456000000.0,52658000000.0,13797000000.0,9667000000.0,4130000000.0,4130000000.0,Healthcare,Drug Manufacturers - Specialty & Generic,1006233990,929.15
2,2023-03-31 00:00:00,NaN,1012204139.0,1012204139.0,6754000000.0,11949000000.0,116209000000.0,186790000000.0,44857000000.0,116209000000.0,...,-250000000.0,44418000000.0,12066000000.0,7188000000.0,4878000000.0,4878000000.0,Healthcare,Drug Manufacturers - Specialty & Generic,1006233990,929.15
3,2022-03-31 00:00:00,NaN,1023742600.0,1023742600.0,35382000000.0,42209000000.0,105078000000.0,211956000000.0,44220000000.0,105078000000.0,...,-236000000.0,33639000000.0,34810000000.0,28232000000.0,6578000000.0,6578000000.0,Healthcare,Drug Manufacturers - Specialty & Generic,1006233990,929.15
4,2021-03-31 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Healthcare,Drug Manufacturers - Specialty & Generic,1006233990,929.15

:

In [2]:
folder2 = 'income_statement'
income_statement = {}
errors = {}

if not os.path.isdir(folder2):
    print(f"Directory not found: {folder2}")
else:
    files = sorted([f for f in os.listdir(folder2) if f.lower().endswith('.csv')])
    if not files:
        print(f"No CSV files found in {folder2}")
    else:
        for fname in files:
            path = os.path.join(folder2, fname)
            try:
                df_is = pd.read_csv(path)
                df_is = df_is.T
                df_col = df_is.iloc[0]
                df_is.columns = df_col
                df_is = df_is[1:].reset_index()
                
                df_is = df_is.rename(columns={'index': 'date'}) 
                income_statement[fname] = df_is
                print(f"Loaded {fname} -> shape: {df_is.shape}")
            except Exception as e:
                errors[fname] = str(e)
                print(f"Failed to load {fname}: {e}")

if errors:
    print("Errors for some files:")
    for f, err in errors.items():
        print(f, ":", err)

Loaded 360ONE.NS.csv -> shape: (4, 53)
Loaded 3MINDIA.NS.csv -> shape: (5, 53)
Loaded AADHARHFC.NS.csv -> shape: (4, 51)
Loaded AARTIIND.NS.csv -> shape: (4, 53)
Loaded AAVAS.NS.csv -> shape: (4, 51)
Loaded ABB.NS.csv -> shape: (5, 53)
Loaded ABBOTINDIA.NS.csv -> shape: (4, 51)
Loaded ABCAPITAL.NS.csv -> shape: (5, 47)
Loaded ABFRL.NS.csv -> shape: (4, 54)
Loaded ABREL.NS.csv -> shape: (4, 53)
Loaded ABSLAMC.NS.csv -> shape: (4, 52)
Loaded ACC.NS.csv -> shape: (5, 53)
Loaded ACE.NS.csv -> shape: (4, 52)
Loaded ACMESOLAR.NS.csv -> shape: (4, 53)
Loaded ADANIENSOL.NS.csv -> shape: (5, 54)
Loaded ADANIENT.NS.csv -> shape: (4, 52)
Loaded ADANIGREEN.NS.csv -> shape: (5, 54)
Loaded ADANIPORTS.NS.csv -> shape: (5, 52)
Loaded ADANIPOWER.NS.csv -> shape: (5, 53)
Loaded ADVENTHTL.NS.csv -> shape: (2, 29)
Loaded AEGISLOG.NS.csv -> shape: (4, 53)
Loaded AEGISVOPAK.NS.csv -> shape: (3, 50)
Loaded AFCONS.NS.csv -> shape: (4, 52)
Loaded AFFLE.NS.csv -> shape: (4, 55)
Loaded AGARWALEYE.NS.csv -> shape: (4, 54)
Loaded AIAENG.NS.csv -> shape: (4, 53)
Loaded AIIL.NS.csv -> shape: (5, 53)
Loaded AJANTPHARM.NS.csv -> shape: (5, 53)
Loaded AKUMS.NS.csv -> shape: (5, 54)
Loaded AKZOINDIA.NS.csv -> shape: (4, 52)
Loaded ALKEM.NS.csv -> shape: (5, 54)
Loaded ALKYLAMINE.NS.csv -> shape: (5, 53)
Loaded ALOKINDS.NS.csv -> shape: (5, 52)
Loaded AMBER.NS.csv -> shape: (4, 55)
Loaded AMBUJACEM.NS.csv -> shape: (4, 54)
Loaded ANANDRATHI.NS.csv -> shape: (5, 52)
Loaded ANANTRAJ.NS.csv -> shape: (4, 50)
Loaded ANGELONE.NS.csv -> shape: (5, 53)
Loaded APARINDS.NS.csv -> shape: (5, 53)
Loaded APLAPOLLO.NS.csv -> shape: (5, 53)
Loaded APLLTD.NS.csv -> shape: (5, 52)
Loaded APOLLOHOSP.NS.csv -> shape: (5, 54)
Loaded APOLLOTYRE.NS.csv -> shape: (4, 54)
Loaded APTUS.NS.csv -> shape: (5, 35)
Loaded ARE&M.NS.csv -> shape: (4, 53)
Loaded ASAHIINDIA.NS.csv -> shape: (5, 51)
Loaded ASHOKLEY.NS.csv -> shape: (5, 55)
Loaded ASIANPAINT.NS.csv -> shape: (5, 53)
Loaded ASTERDM.NS.csv -> shape: (5, 54)
Loaded ASTRAL.NS.csv -> shape: (5, 54)
Loaded ASTRAZEN.NS.csv -> shape: (4, 52)
Loaded ATGL.NS.csv -> shape: (5, 53)
Loaded ATHERENERG.NS.csv -> shape: (3, 52)
Loaded ATUL.NS.csv -> shape: (5, 54)
Loaded AUBANK.NS.csv -> shape: (5, 38)
Loaded AUROPHARMA.NS.csv -> shape: (5, 56)
Loaded AWL.NS.csv -> shape: (5, 53)
Loaded AXISBANK.NS.csv -> shape: (5, 41)
Loaded BAJAJ-AUTO.NS.csv -> shape: (4, 52)
Loaded BAJAJFINSV.NS.csv -> shape: (4, 44)
Loaded BAJAJHFL.NS.csv -> shape: (4, 52)
Loaded BAJAJHLDNG.NS.csv -> shape: (4, 33)
Loaded BAJFINANCE.NS.csv -> shape: (4, 39)
Loaded BALKRISIND.NS.csv -> shape: (4, 52)
Loaded BALRAMCHIN.NS.csv -> shape: (4, 52)
Loaded BANDHANBNK.NS.csv -> shape: (4, 40)
Loaded BANKBARODA.NS.csv -> shape: (4, 40)
Loaded BANKINDIA.NS.csv -> shape: (4, 39)
Loaded BASF.NS.csv -> shape: (5, 52)
Loaded BATAINDIA.NS.csv -> shape: (5, 53)
Loaded BAYERCROP.NS.csv -> shape: (5, 53)
Loaded BBTC.NS.csv -> shape: (4, 56)
Loaded BDL.NS.csv -> shape: (5, 54)
Loaded BEL.NS.csv -> shape: (4, 54)
Loaded BEML.NS.csv -> shape: (4, 53)
Loaded BERGEPAINT.NS.csv -> shape: (4, 53)
Loaded BHARATFORG.NS.csv -> shape: (5, 55)
Loaded BHARTIARTL.NS.csv -> shape: (5, 55)
Loaded BHARTIHEXA.NS.csv -> shape: (4, 50)
Loaded BHEL.NS.csv -> shape: (5, 54)
Loaded BIKAJI.NS.csv -> shape: (4, 54)
Loaded BIOCON.NS.csv -> shape: (5, 55)
Loaded BLS.NS.csv -> shape: (4, 53)
Loaded BLUEDART.NS.csv -> shape: (5, 49)
Loaded BLUEJET.NS.csv -> shape: (5, 52)
Loaded BLUESTARCO.NS.csv -> shape: (5, 54)
Loaded BOSCHLTD.NS.csv -> shape: (5, 53)
Loaded BPCL.NS.csv -> shape: (4, 51)
Loaded BRIGADE.NS.csv -> shape: (5, 54)
Loaded BRITANNIA.NS.csv -> shape: (5, 54)
Loaded BSE.NS.csv -> shape: (4, 53)
Loaded BSOFT.NS.csv -> shape: (5, 52)
Loaded CAMPUS.NS.csv -> shape: (5, 54)
Loaded CAMS.NS.csv -> shape: (4, 53)
Loaded CANBK.NS.csv -> shape: (4, 39)
Loaded CANFINHOME.NS.csv -> shape: (5, 37)
Loaded CAPLIPOINT.NS.csv -> shape: (5, 52)
Loaded CARBORUNIV.NS.csv -> shape: (4, 54)
Loaded CASTROLIND.NS.csv -> shape: (5, 52)
Loaded CCL.NS.csv -> shape: (4, 53)
Loaded CDSL.NS.csv -> shape: (4, 52)
Loaded CEATLTD.NS.csv -> shape: (5, 52)
Loaded CENTRALBK.NS.csv -> shape: (5, 41)
Loaded CENTURYPLY.NS.csv -> shape: (5, 54)
Loaded CERA.NS.csv -> shape: (5, 55)
Loaded CESC.NS.csv -> shape: (4, 52)
Loaded CGCL.NS.csv -> shape: (5, 52)
Loaded CGPOWER.NS.csv -> shape: (5, 56)
Loaded CHALET.NS.csv -> shape: (5, 55)
Loaded CHAMBLFERT.NS.csv -> shape: (5, 55)
Loaded CHENNPETRO.NS.csv -> shape: (4, 50)
Loaded CHOICEIN.NS.csv -> shape: (5, 54)
Loaded CHOLAFIN.NS.csv -> shape: (5, 40)
Loaded CHOLAHLDNG.NS.csv -> shape: (4, 52)
Loaded CIPLA.NS.csv -> shape: (4, 54)
Loaded CLEAN.NS.csv -> shape: (5, 53)
Loaded COALINDIA.NS.csv -> shape: (5, 52)
Loaded COCHINSHIP.NS.csv -> shape: (5, 55)
Loaded COFORGE.NS.csv -> shape: (5, 53)
Loaded COHANCE.NS.csv -> shape: (5, 55)
Loaded COLPAL.NS.csv -> shape: (4, 51)
Loaded CONCOR.NS.csv -> shape: (4, 53)
Loaded CONCORDBIO.NS.csv -> shape: (5, 52)
Loaded COROMANDEL.NS.csv -> shape: (5, 53)
Loaded CRAFTSMAN.NS.csv -> shape: (4, 54)
Loaded CREDITACC.NS.csv -> shape: (5, 51)
Loaded CRISIL.NS.csv -> shape: (4, 51)
Loaded CROMPTON.NS.csv -> shape: (5, 53)
Loaded CUB.NS.csv -> shape: (4, 38)
Loaded CUMMINSIND.NS.csv -> shape: (5, 52)
Loaded CYIENT.NS.csv -> shape: (5, 52)
Loaded DABUR.NS.csv -> shape: (4, 53)
Loaded DALBHARAT.NS.csv -> shape: (4, 54)
Loaded DATAPATTNS.NS.csv -> shape: (5, 52)
Loaded DBREALTY.NS.csv -> shape: (5, 54)
Loaded DCMSHRIRAM.NS.csv -> shape: (5, 53)
Loaded DEEPAKFERT.NS.csv -> shape: (4, 54)
Loaded DEEPAKNTR.NS.csv -> shape: (4, 53)
Loaded DELHIVERY.NS.csv -> shape: (5, 52)
Loaded DEVYANI.NS.csv -> shape: (5, 55)
Loaded DIVISLAB.NS.csv -> shape: (4, 53)
Loaded DIXON.NS.csv -> shape: (5, 54)
Loaded DLF.NS.csv -> shape: (4, 53)
Loaded DMART.NS.csv -> shape: (4, 51)
Loaded DOMS.NS.csv -> shape: (4, 52)
Loaded DRREDDY.NS.csv -> shape: (5, 51)
Loaded ECLERX.NS.csv -> shape: (5, 54)
Loaded EICHERMOT.NS.csv -> shape: (5, 54)
Loaded EIDPARRY.NS.csv -> shape: (5, 56)
Loaded EIHOTEL.NS.csv -> shape: (5, 57)
Loaded ELECON.NS.csv -> shape: (4, 53)
Loaded ELGIEQUIP.NS.csv -> shape: (5, 55)
Loaded EMAMILTD.NS.csv -> shape: (4, 53)
Loaded EMCURE.NS.csv -> shape: (5, 56)
Loaded ENDURANCE.NS.csv -> shape: (5, 54)
Loaded ENGINERSIN.NS.csv -> shape: (5, 56)
Loaded ENRIN.NS.csv -> shape: (2, 37)
Loaded ERIS.NS.csv -> shape: (5, 55)
Loaded ESCORTS.NS.csv -> shape: (5, 56)
Loaded ETERNAL.NS.csv -> shape: (5, 54)
Loaded EXIDEIND.NS.csv -> shape: (5, 54)
Loaded FACT.NS.csv -> shape: (5, 54)
Loaded FEDERALBNK.NS.csv -> shape: (5, 40)
Loaded FINCABLES.NS.csv -> shape: (4, 52)
Loaded FINPIPE.NS.csv -> shape: (5, 51)
Loaded FIRSTCRY.NS.csv -> shape: (5, 55)
Loaded FIVESTAR.NS.csv -> shape: (4, 52)
Loaded FLUOROCHEM.NS.csv -> shape: (4, 53)
Loaded FORCEMOT.NS.csv -> shape: (5, 53)
Loaded FORTIS.NS.csv -> shape: (4, 56)
Loaded FSL.NS.csv -> shape: (5, 55)
Loaded GAIL.NS.csv -> shape: (4, 53)
Loaded GESHIP.NS.csv -> shape: (4, 49)
Loaded GICRE.NS.csv -> shape: (4, 43)
Loaded GILLETTE.NS.csv -> shape: (4, 50)
Loaded GLAND.NS.csv -> shape: (4, 54)
Loaded GLAXO.NS.csv -> shape: (5, 54)
Loaded GLENMARK.NS.csv -> shape: (4, 55)
Loaded GMDCLTD.NS.csv -> shape: (5, 52)
Loaded GMRAIRPORT.NS.csv -> shape: (5, 50)
Loaded GODFRYPHLP.NS.csv -> shape: (5, 56)
Loaded GODIGIT.NS.csv -> shape: (4, 42)
Loaded GODREJAGRO.NS.csv -> shape: (5, 56)
Loaded GODREJCP.NS.csv -> shape: (5, 55)
Loaded GODREJIND.NS.csv -> shape: (5, 57)
Loaded GODREJPROP.NS.csv -> shape: (5, 53)
Loaded GPIL.NS.csv -> shape: (5, 54)
Loaded GRANULES.NS.csv -> shape: (5, 55)
Loaded GRAPHITE.NS.csv -> shape: (4, 53)
Loaded GRASIM.NS.csv -> shape: (5, 56)
Loaded GRAVITA.NS.csv -> shape: (4, 53)
Loaded GRSE.NS.csv -> shape: (5, 53)
Loaded GSPL.NS.csv -> shape: (5, 54)
Loaded GUJGASLTD.NS.csv -> shape: (4, 52)
Loaded GVT&D.NS.csv -> shape: (5, 54)
Loaded HAL.NS.csv -> shape: (5, 55)
Loaded HAPPSTMNDS.NS.csv -> shape: (5, 54)
Loaded HAVELLS.NS.csv -> shape: (5, 54)
Loaded HBLENGINE.NS.csv -> shape: (5, 55)
Loaded HCLTECH.NS.csv -> shape: (5, 51)
Loaded HDFCAMC.NS.csv -> shape: (5, 51)
Loaded HDFCBANK.NS.csv -> shape: (5, 42)
Loaded HDFCLIFE.NS.csv -> shape: (4, 42)
Loaded HEG.NS.csv -> shape: (5, 52)
Loaded HEROMOTOCO.NS.csv -> shape: (5, 52)
Loaded HEXT.NS.csv -> shape: (5, 54)
Loaded HFCL.NS.csv -> shape: (5, 53)
Loaded HINDALCO.NS.csv -> shape: (5, 54)
Loaded HINDCOPPER.NS.csv -> shape: (5, 55)
Loaded HINDPETRO.NS.csv -> shape: (4, 49)
Loaded HINDUNILVR.NS.csv -> shape: (5, 54)
Loaded HINDZINC.NS.csv -> shape: (4, 47)
Loaded HOMEFIRST.NS.csv -> shape: (4, 51)
Loaded HONASA.NS.csv -> shape: (5, 55)
Loaded HONAUT.NS.csv -> shape: (5, 52)
Loaded HSCL.NS.csv -> shape: (5, 54)
Loaded HUDCO.NS.csv -> shape: (4, 38)
Loaded HYUNDAI.NS.csv -> shape: (4, 50)
Loaded ICICIBANK.NS.csv -> shape: (5, 45)
Loaded ICICIGI.NS.csv -> shape: (5, 45)
Loaded ICICIPRULI.NS.csv -> shape: (4, 43)
Loaded IDBI.NS.csv -> shape: (4, 39)
Loaded IDEA.NS.csv -> shape: (5, 53)
Loaded IDFCFIRSTB.NS.csv -> shape: (5, 40)
Loaded IEX.NS.csv -> shape: (5, 51)
Loaded IFCI.NS.csv -> shape: (5, 41)
Loaded IGIL.NS.csv -> shape: (4, 53)
Loaded IGL.NS.csv -> shape: (4, 52)
Loaded IIFL.NS.csv -> shape: (4, 40)
Loaded IKS.NS.csv -> shape: (4, 52)
Loaded INDGN.NS.csv -> shape: (5, 51)
Loaded INDHOTEL.NS.csv -> shape: (5, 54)
Loaded INDIACEM.NS.csv -> shape: (5, 55)
Loaded INDIAMART.NS.csv -> shape: (4, 51)
Loaded INDIANB.NS.csv -> shape: (4, 39)
Loaded INDIGO.NS.csv -> shape: (4, 51)
Loaded INDUSINDBK.NS.csv -> shape: (4, 38)
Loaded INDUSTOWER.NS.csv -> shape: (4, 49)
Loaded INFY.NS.csv -> shape: (5, 56)
Loaded INOXINDIA.NS.csv -> shape: (5, 53)
Loaded INOXWIND.NS.csv -> shape: (4, 54)
Loaded INTELLECT.NS.csv -> shape: (4, 53)
Loaded IOB.NS.csv -> shape: (4, 38)
Loaded IOC.NS.csv -> shape: (4, 50)
Loaded IPCALAB.NS.csv -> shape: (5, 56)
Loaded IRB.NS.csv -> shape: (5, 52)
Loaded IRCON.NS.csv -> shape: (5, 54)
Loaded IRCTC.NS.csv -> shape: (5, 49)
Loaded IREDA.NS.csv -> shape: (5, 53)
Loaded IRFC.NS.csv -> shape: (4, 53)
Loaded ITC.NS.csv -> shape: (5, 54)
Loaded ITCHOTELS.NS.csv -> shape: (1, 52)
Loaded ITI.NS.csv -> shape: (5, 53)
Loaded J&KBANK.NS.csv -> shape: (5, 40)
Loaded JBCHEPHARM.NS.csv -> shape: (5, 52)
Loaded JBMA.NS.csv -> shape: (5, 53)
Loaded JINDALSAW.NS.csv -> shape: (4, 53)
Loaded JINDALSTEL.NS.csv -> shape: (5, 56)
Loaded JIOFIN.NS.csv -> shape: (4, 50)
Loaded JKCEMENT.NS.csv -> shape: (4, 54)
Loaded JKTYRE.NS.csv -> shape: (5, 54)
Loaded JMFINANCIL.NS.csv -> shape: (5, 35)
Loaded JPPOWER.NS.csv -> shape: (5, 57)
Loaded JSL.NS.csv -> shape: (4, 53)
Loaded JSWENERGY.NS.csv -> shape: (4, 53)
Loaded JSWINFRA.NS.csv -> shape: (5, 53)
Loaded JSWSTEEL.NS.csv -> shape: (4, 53)
Loaded JUBLFOOD.NS.csv -> shape: (4, 54)
Loaded JUBLINGREA.NS.csv -> shape: (5, 53)
Loaded JUBLPHARMA.NS.csv -> shape: (5, 55)
Loaded JWL.NS.csv -> shape: (5, 50)
Loaded JYOTHYLAB.NS.csv -> shape: (5, 53)
Loaded JYOTICNC.NS.csv -> shape: (4, 50)
Loaded KAJARIACER.NS.csv -> shape: (4, 55)
Loaded KALYANKJIL.NS.csv -> shape: (4, 54)
Loaded KARURVYSYA.NS.csv -> shape: (5, 38)
Loaded KAYNES.NS.csv -> shape: (4, 53)
Loaded KEC.NS.csv -> shape: (4, 52)
Loaded KEI.NS.csv -> shape: (4, 55)
Loaded KFINTECH.NS.csv -> shape: (4, 53)
Loaded KIMS.NS.csv -> shape: (5, 54)
Loaded KIRLOSBROS.NS.csv -> shape: (4, 53)
Loaded KIRLOSENG.NS.csv -> shape: (4, 53)
Loaded KOTAKBANK.NS.csv -> shape: (5, 41)
Loaded KPIL.NS.csv -> shape: (4, 54)
Loaded KPITTECH.NS.csv -> shape: (5, 54)
Loaded KPRMILL.NS.csv -> shape: (5, 53)
Loaded KSB.NS.csv -> shape: (5, 50)
Loaded LALPATHLAB.NS.csv -> shape: (4, 52)
Loaded LATENTVIEW.NS.csv -> shape: (5, 53)
Loaded LAURUSLABS.NS.csv -> shape: (5, 54)
Loaded LEMONTREE.NS.csv -> shape: (5, 53)
Loaded LICHSGFIN.NS.csv -> shape: (5, 39)
Loaded LICI.NS.csv -> shape: (5, 40)
Loaded LINDEINDIA.NS.csv -> shape: (5, 51)
Loaded LLOYDSME.NS.csv -> shape: (5, 54)
Loaded LODHA.NS.csv -> shape: (5, 53)
Loaded LT.NS.csv -> shape: (5, 56)
Loaded LTF.NS.csv -> shape: (5, 41)
Loaded LTFOODS.NS.csv -> shape: (4, 54)
Loaded LTIM.NS.csv -> shape: (5, 53)
Loaded LTTS.NS.csv -> shape: (4, 51)
Loaded LUPIN.NS.csv -> shape: (5, 54)
Loaded M&M.NS.csv -> shape: (5, 56)
Loaded M&MFIN.NS.csv -> shape: (5, 40)
Loaded MAHABANK.NS.csv -> shape: (4, 39)
Loaded MAHSCOOTER.NS.csv -> shape: (5, 49)
Loaded MAHSEAMLES.NS.csv -> shape: (4, 52)
Loaded MANAPPURAM.NS.csv -> shape: (4, 40)
Loaded MANKIND.NS.csv -> shape: (4, 55)
Loaded MANYAVAR.NS.csv -> shape: (4, 51)
Loaded MAPMYINDIA.NS.csv -> shape: (4, 53)
Loaded MARICO.NS.csv -> shape: (5, 54)
Loaded MARUTI.NS.csv -> shape: (5, 52)
Loaded MAXHEALTH.NS.csv -> shape: (4, 53)
Loaded MAZDOCK.NS.csv -> shape: (4, 50)
Loaded MCX.NS.csv -> shape: (5, 52)
Loaded MEDANTA.NS.csv -> shape: (4, 54)
Loaded METROPOLIS.NS.csv -> shape: (5, 54)
Loaded MFSL.NS.csv -> shape: (5, 48)
Loaded MGL.NS.csv -> shape: (4, 51)
Loaded MINDACORP.NS.csv -> shape: (5, 55)
Loaded MMTC.NS.csv -> shape: (4, 53)
Loaded MOTHERSON.NS.csv -> shape: (5, 57)
Loaded MOTILALOFS.NS.csv -> shape: (5, 54)
Loaded MPHASIS.NS.csv -> shape: (4, 49)
Loaded MRF.NS.csv -> shape: (5, 55)
Loaded MRPL.NS.csv -> shape: (4, 50)
Loaded MSUMI.NS.csv -> shape: (4, 51)
Loaded MUTHOOTFIN.NS.csv -> shape: (5, 41)
Loaded NAM-INDIA.NS.csv -> shape: (5, 52)
Loaded NATCOPHARM.NS.csv -> shape: (5, 54)
Loaded NATIONALUM.NS.csv -> shape: (5, 52)
Loaded NAUKRI.NS.csv -> shape: (5, 54)
Loaded NAVA.NS.csv -> shape: (4, 53)
Loaded NAVINFLUOR.NS.csv -> shape: (4, 50)
Loaded NBCC.NS.csv -> shape: (5, 56)
Loaded NCC.NS.csv -> shape: (5, 52)
Loaded NESTLEIND.NS.csv -> shape: (4, 51)
Loaded NETWEB.NS.csv -> shape: (4, 52)
Loaded NEULANDLAB.NS.csv -> shape: (4, 51)
Loaded NEWGEN.NS.csv -> shape: (4, 53)
Loaded NH.NS.csv -> shape: (5, 55)
Loaded NHPC.NS.csv -> shape: (5, 54)
Loaded NIACL.NS.csv -> shape: (5, 45)
Loaded NIVABUPA.NS.csv -> shape: (4, 43)
Loaded NLCINDIA.NS.csv -> shape: (4, 53)
Loaded NMDC.NS.csv -> shape: (5, 55)
Loaded NSLNISP.NS.csv -> shape: (5, 52)
Loaded NTPC.NS.csv -> shape: (5, 54)
Loaded NTPCGREEN.NS.csv -> shape: (3, 52)
Loaded NUVAMA.NS.csv -> shape: (3, 54)
Loaded NUVOCO.NS.csv -> shape: (4, 51)
Loaded NYKAA.NS.csv -> shape: (4, 53)
Loaded OBEROIRLTY.NS.csv -> shape: (4, 51)
Loaded OFSS.NS.csv -> shape: (4, 50)
Loaded OIL.NS.csv -> shape: (5, 49)
Loaded OLAELEC.NS.csv -> shape: (5, 53)
Loaded OLECTRA.NS.csv -> shape: (5, 54)
Loaded ONESOURCE.NS.csv -> shape: (3, 56)
Loaded ONGC.NS.csv -> shape: (4, 51)
Loaded PAGEIND.NS.csv -> shape: (5, 51)
Loaded PATANJALI.NS.csv -> shape: (5, 53)
Loaded PAYTM.NS.csv -> shape: (4, 54)
Loaded PCBL.NS.csv -> shape: (5, 55)
Loaded PERSISTENT.NS.csv -> shape: (4, 52)
Loaded PETRONET.NS.csv -> shape: (5, 49)
Loaded PFC.NS.csv -> shape: (4, 39)
Loaded PFIZER.NS.csv -> shape: (5, 52)
Loaded PGEL.NS.csv -> shape: (5, 55)
Loaded PGHH.NS.csv -> shape: (4, 51)
Loaded PHOENIXLTD.NS.csv -> shape: (5, 53)
Loaded PIDILITIND.NS.csv -> shape: (4, 53)
Loaded PIIND.NS.csv -> shape: (5, 52)
Loaded PNB.NS.csv -> shape: (4, 39)
Loaded PNBHOUSING.NS.csv -> shape: (5, 39)
Loaded POLICYBZR.NS.csv -> shape: (5, 54)
Loaded POLYCAB.NS.csv -> shape: (5, 55)
Loaded POLYMED.NS.csv -> shape: (4, 54)
Loaded POONAWALLA.NS.csv -> shape: (5, 55)
Loaded POWERGRID.NS.csv -> shape: (5, 54)
Loaded POWERINDIA.NS.csv -> shape: (5, 52)
Loaded PPLPHARMA.NS.csv -> shape: (5, 55)
Loaded PRAJIND.NS.csv -> shape: (4, 52)
Loaded PREMIERENE.NS.csv -> shape: (4, 53)
Loaded PRESTIGE.NS.csv -> shape: (5, 53)
Loaded PTCIL.NS.csv -> shape: (5, 53)
Loaded PVRINOX.NS.csv -> shape: (4, 53)
Loaded RADICO.NS.csv -> shape: (4, 53)
Loaded RAILTEL.NS.csv -> shape: (5, 53)
Loaded RAINBOW.NS.csv -> shape: (4, 53)
Loaded RAMCOCEM.NS.csv -> shape: (4, 53)
Loaded RBLBANK.NS.csv -> shape: (5, 39)
Loaded RCF.NS.csv -> shape: (4, 54)
Loaded RECLTD.NS.csv -> shape: (5, 40)
Loaded REDINGTON.NS.csv -> shape: (5, 54)
Loaded RELIANCE.NS.csv -> shape: (5, 51)
Loaded RELINFRA.NS.csv -> shape: (4, 51)
Loaded RHIM.NS.csv -> shape: (5, 53)
Loaded RITES.NS.csv -> shape: (4, 55)
Loaded RKFORGE.NS.csv -> shape: (5, 54)
Loaded RPOWER.NS.csv -> shape: (5, 54)
Loaded RRKABEL.NS.csv -> shape: (4, 54)
Loaded RVNL.NS.csv -> shape: (4, 53)
Loaded SAGILITY.NS.csv -> shape: (3, 51)
Loaded SAIL.NS.csv -> shape: (4, 52)
Loaded SAILIFE.NS.csv -> shape: (4, 53)
Loaded SAMMAANCAP.NS.csv -> shape: (5, 45)
Loaded SAPPHIRE.NS.csv -> shape: (5, 54)
Loaded SARDAEN.NS.csv -> shape: (5, 52)
Loaded SAREGAMA.NS.csv -> shape: (4, 56)
Loaded SBFC.NS.csv -> shape: (4, 52)
Loaded SBICARD.NS.csv -> shape: (5, 39)
Loaded SBILIFE.NS.csv -> shape: (5, 39)
Loaded SBIN.NS.csv -> shape: (4, 39)
Loaded SCHAEFFLER.NS.csv -> shape: (5, 53)
Loaded SCHNEIDER.NS.csv -> shape: (5, 53)
Loaded SCI.NS.csv -> shape: (5, 51)
Loaded SHREECEM.NS.csv -> shape: (5, 52)
Loaded SHRIRAMFIN.NS.csv -> shape: (4, 41)
Loaded SHYAMMETL.NS.csv -> shape: (4, 54)
Loaded SIEMENS.NS.csv -> shape: (5, 56)
Loaded SIGNATURE.NS.csv -> shape: (4, 53)
Loaded SJVN.NS.csv -> shape: (5, 56)
Loaded SKFINDIA.NS.csv -> shape: (4, 51)
Loaded SOBHA.NS.csv -> shape: (4, 54)
Loaded SOLARINDS.NS.csv -> shape: (5, 51)
Loaded SONACOMS.NS.csv -> shape: (5, 54)
Loaded SONATSOFTW.NS.csv -> shape: (5, 54)
Loaded SRF.NS.csv -> shape: (5, 54)
Loaded STARHEALTH.NS.csv -> shape: (4, 42)
Loaded SUMICHEM.NS.csv -> shape: (5, 55)
Loaded SUNDARMFIN.NS.csv -> shape: (4, 40)
Loaded SUNDRMFAST.NS.csv -> shape: (4, 52)
Loaded SUNPHARMA.NS.csv -> shape: (4, 54)
Loaded SUNTV.NS.csv -> shape: (4, 52)
Loaded SUPREMEIND.NS.csv -> shape: (5, 51)
Loaded SUZLON.NS.csv -> shape: (5, 58)
Loaded SWANCORP.NS.csv -> shape: (5, 53)
Loaded SWIGGY.NS.csv -> shape: (4, 53)
Loaded SYNGENE.NS.csv -> shape: (4, 53)
Loaded SYRMA.NS.csv -> shape: (4, 54)
Loaded TARIL.NS.csv -> shape: (4, 52)
Loaded TATACHEM.NS.csv -> shape: (4, 56)
Loaded TATACOMM.NS.csv -> shape: (4, 55)
Loaded TATACONSUM.NS.csv -> shape: (5, 54)
Loaded TATAELXSI.NS.csv -> shape: (5, 51)
Loaded TATAINVEST.NS.csv -> shape: (4, 34)
Loaded TATAPOWER.NS.csv -> shape: (5, 57)
Loaded TATASTEEL.NS.csv -> shape: (5, 54)
Loaded TATATECH.NS.csv -> shape: (5, 51)
Loaded TBOTEK.NS.csv -> shape: (5, 54)
Loaded TCS.NS.csv -> shape: (4, 48)
Loaded TECHM.NS.csv -> shape: (4, 53)
Loaded TECHNOE.NS.csv -> shape: (5, 53)
Loaded TEJASNET.NS.csv -> shape: (5, 53)
Loaded THELEELA.NS.csv -> shape: (4, 54)
Loaded THERMAX.NS.csv -> shape: (5, 54)
Loaded TIINDIA.NS.csv -> shape: (4, 57)
Loaded TIMKEN.NS.csv -> shape: (5, 51)
Loaded TITAGARH.NS.csv -> shape: (5, 54)
Loaded TITAN.NS.csv -> shape: (4, 53)
Loaded TMPV.NS.csv -> shape: (5, 61)
Loaded TORNTPHARM.NS.csv -> shape: (4, 52)
Loaded TORNTPOWER.NS.csv -> shape: (5, 53)
Loaded TRENT.NS.csv -> shape: (5, 53)
Loaded TRIDENT.NS.csv -> shape: (5, 53)
Loaded TRITURBINE.NS.csv -> shape: (5, 54)
Loaded TRIVENI.NS.csv -> shape: (4, 55)
Loaded TTML.NS.csv -> shape: (5, 53)
Loaded TVSMOTOR.NS.csv -> shape: (5, 52)
Loaded UBL.NS.csv -> shape: (5, 55)
Loaded UCOBANK.NS.csv -> shape: (4, 38)
Loaded ULTRACEMCO.NS.csv -> shape: (5, 55)
Loaded UNIONBANK.NS.csv -> shape: (4, 40)
Loaded UNITDSPR.NS.csv -> shape: (5, 54)
Loaded UNOMINDA.NS.csv -> shape: (4, 56)
Loaded UPL.NS.csv -> shape: (4, 55)
Loaded USHAMART.NS.csv -> shape: (5, 55)
Loaded UTIAMC.NS.csv -> shape: (5, 53)
Loaded VBL.NS.csv -> shape: (4, 54)
Loaded VEDL.NS.csv -> shape: (5, 59)
Loaded VENTIVE.NS.csv -> shape: (4, 54)
Loaded VGUARD.NS.csv -> shape: (5, 52)
Loaded VIJAYA.NS.csv -> shape: (5, 54)
Loaded VMM.NS.csv -> shape: (4, 51)
Loaded VOLTAS.NS.csv -> shape: (5, 52)
Loaded VTL.NS.csv -> shape: (5, 52)
Loaded WAAREEENER.NS.csv -> shape: (4, 54)
Loaded WELCORP.NS.csv -> shape: (5, 54)
Loaded WELSPUNLIV.NS.csv -> shape: (4, 54)
Loaded WHIRLPOOL.NS.csv -> shape: (4, 54)
Loaded WIPRO.NS.csv -> shape: (5, 54)
Loaded WOCKPHARMA.NS.csv -> shape: (5, 56)
Loaded YESBANK.NS.csv -> shape: (5, 40)
Loaded ZEEL.NS.csv -> shape: (5, 55)
Loaded ZENSARTECH.NS.csv -> shape: (5, 54)
Loaded ZENTEC.NS.csv -> shape: (5, 54)
Loaded ZFCVINDIA.NS.csv -> shape: (5, 53)

In [3]:
df_combined = pd.DataFrame()
for cname, df_bs in balance_sheets.items():
    df_bs['company'] = cname.split('.')[0]
    df_combined = pd.concat([df_combined, df_bs])

In [4]:
df_combined_financial = pd.DataFrame()
for cname, df_is in income_statement.items():
    df_is['company'] = cname.split('.')[0]
    df_combined_financial = pd.concat([df_combined_financial, df_is])

In [5]:
# Convert to datetime
df_combined['date'] = pd.to_datetime(df_combined['date'], errors='coerce')

# Now check again
print(df_combined['date'].dtypes)

# Convert to datetime
df_combined_financial['date'] = pd.to_datetime(df_combined_financial['date'], errors='coerce')

# Now check again
print(df_combined_financial['date'].dtypes)

datetime64[ns]
datetime64[ns]

In [6]:
df_combined_financial.reset_index(drop=True, inplace=True)
df_combined.reset_index(drop=True, inplace=True)

In [7]:
df_final = df_combined_financial.merge(df_combined, on=['company','date'], how='left')

In [8]:
# --- 1. Basic Working Capital Metrics ---
df_final['Working_Capital'] = df_final['Current Assets'] - df_final['Current Liabilities']
df_final['Working_Capital_Ratio'] = df_final['Current Assets'] / df_final['Current Liabilities']
df_final['Cash_Ratio'] = df_final['Cash And Cash Equivalents'] / df_final['Current Liabilities']

In [10]:
df_final

Unnamed: 0,date,Tax Effect Of Unusual Items,Tax Rate For Calcs,Normalized EBITDA,Total Unusual Items,Total Unusual Items Excluding Goodwill,Net Income From Continuing Operation Net Minority Interest,Reconciled Depreciation,Reconciled Cost Of Revenue,EBITDA,...,Accrued Interest Receivable,Loans Receivable,Interest Payable,Dueto Related Parties Non Current,Dueto Related Parties Current,Duefrom Related Parties Non Current,Duefrom Related Parties Current,Working_Capital,Working_Capital_Ratio,Cash_Ratio
0,2025-03-31,1681575028.585854,0.24615,16126800000.0,6831500000.0,6831500000.0,10153000000.0,705300000.0,8472700000.0,22958300000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19269400000.0,1.206527,0.079333
1,2024-03-31,1415787646.498899,0.2026,10007500000.0,6988100000.0,6988100000.0,8042100000.0,566400000.0,8870200000.0,16995600000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-11320600000.0,0.845525,0.060414
2,2023-03-31,727725411.330252,0.226276,9665000000.0,3216100000.0,3216100000.0,6579300000.0,463100000.0,5468300000.0,12881100000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3867200000.0,0.92774,0.0952
3,2022-03-31,427382350.0,0.0995,7264300000.0,4295300000.0,4295300000.0,5777400000.0,417400000.0,7319200000.0,11559600000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28743600000.0,1.517603,0.08798
4,2025-03-31,-7798813.5,0.3845,8415242000.0,-20283000.0,-20283000.0,4760674000.0,552870000.0,27455107000.0,8394959000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13977157000.0,2.340149,0.894361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2267,2025-03-31,-496192642.739808,0.234274,71128000000.0,-768000000.0,-2118000000.0,45255000000.0,9158000000.0,66664000000.0,70360000000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80045000000.0,1.885297,0.091444
2268,2024-03-31,215668344.111959,0.203269,55109000000.0,1061000000.0,1061000000.0,38365000000.0,7641000000.0,65004000000.0,56170000000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61595000000.0,2.153054,0.077313
2269,2023-03-31,-1130340966.135074,0.226976,33418000000.0,961000000.0,-4980000000.0,19649000000.0,7227000000.0,65589000000.0,34379000000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44857000000.0,1.811055,0.088199
2270,2022-03-31,474180261.442514,0.180297,34256000000.0,2630000000.0,2630000000.0,22416000000.0,7361000000.0,58189000000.0,36886000000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44220000000.0,1.564074,0.083909
2271,2021-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df_final.columns.tolist()

['date',
 'Tax Effect Of Unusual Items',
 'Tax Rate For Calcs',
 'Normalized EBITDA',
 'Total Unusual Items',
 'Total Unusual Items Excluding Goodwill',
 'Net Income From Continuing Operation Net Minority Interest',
 'Reconciled Depreciation',
 'Reconciled Cost Of Revenue',
 'EBITDA',
 'EBIT',
 'Net Interest Income',
 'Interest Expense',
 'Interest Income',
 'Normalized Income',
 'Net Income From Continuing And Discontinued Operation',
 'Total Expenses',
 'Rent Expense Supplemental',
 'Diluted Average Shares',
 'Basic Average Shares',
 'Diluted EPS',
 'Basic EPS',
 'Diluted NI Availto Com Stockholders',
 'Net Income Common Stockholders',
 'Otherunder Preferred Stock Dividend',
 'Net Income',
 'Minority Interests',
 'Net Income Including Noncontrolling Interests',
 'Net Income Continuous Operations',
 'Tax Provision',
 'Pretax Income',
 'Other Non Operating Income Expenses',
 'Special Income Charges',
 'Other Special Charges',
 'Write Off',
 'Net Non Operating Interest Income Expense',
 'Total Other Finance Cost',
 'Interest Expense Non Operating',
 'Interest Income Non Operating',
 'Operating Income',
 'Operating Expense',
 'Other Operating Expenses',
 'Depreciation And Amortization In Income Statement',
 'Amortization',
 'Depreciation Income Statement',
 'Selling General And Administration',
 'Selling And Marketing Expense',
 'General And Administrative Expense',
 'Rent And Landing Fees',
 'Gross Profit',
 'Cost Of Revenue',
 'Total Revenue',
 'Operating Revenue',
 'company',
 'Impairment Of Capital Assets',
 'Net Income Extraordinary',
 'Net Income Discontinuous Operations',
 'Average Dilution Earnings',
 'Other Income Expense',
 'Net Policyholder Benefits And Claims',
 'Restructuring And Mergern Acquisition',
 'Preferred Stock Dividends',
 'Research And Development',
 'Gain On Sale Of Security',
 'Insurance And Claims',
 'Total Operating Income As Reported',
 'Gain On Sale Of Ppe',
 'Earnings From Equity Interest',
 'Depreciation Amortization Depletion Income Statement',
 'Amortization Of Intangibles Income Statement',
 'Other Gand A',
 'Salaries And Wages',
 'Occupancy And Equipment',
 'Other Non Interest Expense',
 'Professional Expense And Contract Services Expense',
 'Gain On Sale Of Business',
 'Other Taxes',
 'Provision For Doubtful Accounts',
 'Earnings From Equity Interest Net Of Tax',
 'Treasury Shares Number',
 'Ordinary Shares Number',
 'Share Issued',
 'Net Debt',
 'Total Debt',
 'Tangible Book Value',
 'Invested Capital',
 'Working Capital',
 'Net Tangible Assets',
 'Capital Lease Obligations',
 'Common Stock Equity',
 'Total Capitalization',
 'Total Equity Gross Minority Interest',
 'Minority Interest',
 'Stockholders Equity',
 'Other Equity Interest',
 'Retained Earnings',
 'Additional Paid In Capital',
 'Capital Stock',
 'Common Stock',
 'Total Liabilities Net Minority Interest',
 'Total Non Current Liabilities Net Minority Interest',
 'Other Non Current Liabilities',
 'Derivative Product Liabilities',
 'Non Current Pension And Other Postretirement Benefit Plans',
 'Non Current Deferred Taxes Liabilities',
 'Long Term Debt And Capital Lease Obligation',
 'Long Term Capital Lease Obligation',
 'Long Term Debt',
 'Long Term Provisions',
 'Current Liabilities',
 'Other Current Liabilities',
 'Current Debt And Capital Lease Obligation',
 'Current Capital Lease Obligation',
 'Current Debt',
 'Pensionand Other Post Retirement Benefit Plans Current',
 'Current Provisions',
 'Payables',
 'Other Payable',
 'Total Tax Payable',
 'Accounts Payable',
 'Total Assets',
 'Total Non Current Assets',
 'Other Non Current Assets',
 'Non Current Deferred Taxes Assets',
 'Financial Assets',
 'Investmentin Financial Assets',
 'Available For Sale Securities',
 'Financial Assets Designatedas Fair Value Through Profitor Loss Total',
 'Goodwill And Other Intangible Assets',
 'Other Intangible Assets',
 'Goodwill',
 'Net PPE',
 'Accumulated Depreciation',
 'Gross PPE',
 'Construction In Progress',
 'Other Properties',
 'Machinery Furniture Equipment',
 'Buildings And Improvements',
 'Land And Improvements',
 'Properties',
 'Current Assets',
 'Other Current Assets',
 'Hedging Assets Current',
 'Restricted Cash',
 'Inventory',
 'Other Receivables',
 'Taxes Receivable',
 'Accounts Receivable',
 'Allowance For Doubtful Accounts Receivable',
 'Gross Accounts Receivable',
 'Cash Cash Equivalents And Short Term Investments',
 'Other Short Term Investments',
 'Cash And Cash Equivalents',
 'Cash Equivalents',
 'Cash Financial',
 'sector',
 'industry',
 'Dividends Payable',
 'Non Current Prepaid Assets',
 'Assets Held For Sale Current',
 'Prepaid Assets',
 'Other Inventories',
 'Finished Goods',
 'Work In Process',
 'Raw Materials',
 'Non Current Deferred Revenue',
 'Other Investments',
 'Long Term Equity Investment',
 'Fixed Assets Revaluation Reserve',
 'Held To Maturity Securities',
 'Investmentsin Joint Venturesat Cost',
 'Investments In Other Ventures Under Equity Method',
 'Non Current Accrued Expenses',
 'Tradeand Other Payables Non Current',
 'Current Deferred Taxes Liabilities',
 'Preferred Securities Outside Stock Equity',
 'Investments And Advances',
 'Investmentsin Associatesat Cost',
 'Investment Properties',
 'Receivables Adjustments Allowances',
 'Treasury Stock',
 'Defined Pension Benefit',
 'Non Current Deferred Assets',
 'Current Deferred Assets',
 'Liabilities Heldfor Sale Non Current',
 'Preferred Stock Equity',
 'Preferred Stock',
 'Trading Securities',
 'Inventories Adjustments Allowances',
 'Investmentsin Subsidiariesat Cost',
 'Receivables',
 'Cash Cash Equivalents And Federal Funds Sold',
 'Preferred Shares Number',
 'Current Deferred Taxes Assets',
 'Gains Losses Not Affecting Retained Earnings',
 'Other Equity Adjustments',
 'Non Current Deferred Liabilities',
 'Current Deferred Liabilities',
 'Current Deferred Revenue',
 'Other Current Borrowings',
 'Line Of Credit',
 'Payables And Accrued Expenses',
 'Current Accrued Expenses',
 'Non Current Accounts Receivable',
 'Current Notes Payable',
 'Foreign Currency Translation Adjustments',
 'Unrealized Gain Loss',
 'Commercial Paper',
 'Notes Receivable',
 'Employee Benefits',
 'Income Tax Payable',
 'Non Current Note Receivables',
 'Accrued Interest Receivable',
 'Loans Receivable',
 'Interest Payable',
 'Dueto Related Parties Non Current',
 'Dueto Related Parties Current',
 'Duefrom Related Parties Non Current',
 'Duefrom Related Parties Current',
 'Working_Capital',
 'Working_Capital_Ratio',
 'Cash_Ratio']

In [9]:
import numpy as np

# Market Cap from yfinance info
df_final['Market_Cap'] = df_final['Shares Outstanding'] * df_final['Current Price']

# Total Liabilities = Total Assets - Equity
df_final['Total_Liabilities'] = df_final['Total Assets'] - df_final['Common Stock Equity']

# Tobin's Q
df_final['Tobins_Q'] = (df_final['Market_Cap'] + df_final['Total_Liabilities']) / df_final['Total Assets']

KeyError: 'Shares Outstanding'

In [9]:
import numpy as np

In [10]:
# # --- 2. Net Trade Cycle (NTC) ---
# # For Inventory Days, Receivable Days, Payable Days we need Sales and COGS (if available).
# # If not in your dataset, you’ll need to merge income statement data.
# # Placeholder calculations (replace with actual Sales/COGS columns when available):

# df_final['Inventory_Days'] = (df_final['Inventory'] / df_final.get('COGS', np.nan)) * 365
# df_final['Receivable_Days'] = (df_final['Accounts Receivable'] / df_final.get('Revenue', np.nan)) * 365
# df_final['Payable_Days'] = (df_final['Accounts Payable'] / df_final.get('COGS', np.nan)) * 365

In [11]:
# --- 4. Control Variables ---
df_final['Liquidity'] = df_final['Working_Capital_Ratio']
df_final['Leverage'] = df_final['Total Debt'] / df_final['Common Stock Equity']
df_final['Size'] = np.log(pd.to_numeric(df_final['Total Assets']))
# df_final['Growth'] = df_final.get('Revenue Growth', np.nan)

In [12]:
import pandas as pd

# Assume df_final has columns: company, year, Total Revenue
df_final['year'] = pd.to_datetime(df_final['date']).dt.year

# Sort by company and year to ensure correct order
df_final = df_final.sort_values(by=['company','year'])

# Replace 0 with NaN to avoid division by zero
df_final['Total Revenue'] = df_final['Total Revenue'].replace(0, np.nan)

# Calculate revenue growth by company
df_final['Revenue_Growth'] = df_final.groupby('company')['Total Revenue'].pct_change()

# If you want percentage format
df_final['Revenue_Growth_pct'] = df_final['Revenue_Growth'] * 100

print(df_final[['company','year','Total Revenue','Revenue_Growth','Revenue_Growth_pct']].head(10))

Unnamed: 0    company  year  Total Revenue  Revenue_Growth  Revenue_Growth_pct
3              360ONE  2022   1.494640e+10             NaN                 NaN
2              360ONE  2023   1.647150e+10        0.102038           10.203795
1              360ONE  2024   2.006120e+10        0.217934           21.793401
0              360ONE  2025   2.635310e+10        0.313635           31.363528
8             3MINDIA  2021            NaN             NaN                 NaN
7             3MINDIA  2022   3.333939e+10             NaN                 NaN
6             3MINDIA  2023   3.957283e+10        0.186969           18.696938
5             3MINDIA  2024   4.186874e+10        0.058017            5.801725
4             3MINDIA  2025   4.442860e+10        0.061140            6.114015
12          AADHARHFC  2022   1.611850e+10             NaN                 NaN

C:\Users\ayush\AppData\Local\Temp\ipykernel_16940\644929146.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_final['Total Revenue'] = df_final['Total Revenue'].replace(0, np.nan)
C:\Users\ayush\AppData\Local\Temp\ipykernel_16940\644929146.py:13: FutureWarning: The default fill_method='ffill' in SeriesGroupBy.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  df_final['Revenue_Growth'] = df_final.groupby('company')['Total Revenue'].pct_change()

In [13]:
df_final['Cash_Ratio']

3        0.08798
2         0.0952
1       0.060414
0       0.079333
8            NaN
          ...
2271         NaN
2270    0.083909
2269    0.088199
2268    0.077313
2267    0.091444
Name: Cash_Ratio, Length: 2272, dtype: object

In [14]:
import numpy as np

# Ensure numeric types
df_final['Inventory'] = pd.to_numeric(df_final['Inventory'], errors='coerce')
df_final['Accounts Receivable'] = pd.to_numeric(df_final['Accounts Receivable'], errors='coerce')
df_final['Accounts Payable'] = pd.to_numeric(df_final['Accounts Payable'], errors='coerce')
df_final['Cost Of Revenue'] = pd.to_numeric(df_final['Cost Of Revenue'], errors='coerce')
df_final['Total Revenue'] = pd.to_numeric(df_final['Total Revenue'], errors='coerce')

# --- Inventory Days ---
df_final['Inventory_Days'] = (df_final['Inventory'] / df_final['Cost Of Revenue'].replace(0, np.nan)) * 365

# --- Receivable Days ---
df_final['Receivable_Days'] = (df_final['Accounts Receivable'] / df_final['Total Revenue'].replace(0, np.nan)) * 365

# --- Payable Days ---
df_final['Payable_Days'] = (df_final['Accounts Payable'] / df_final['Cost Of Revenue'].replace(0, np.nan)) * 365

# --- Net Trade Cycle ---
df_final['NTC'] = df_final['Inventory_Days'] + df_final['Receivable_Days'] - df_final['Payable_Days']

In [15]:


# --- 5. Efficiency Index (Composite Score) ---
# Normalize metrics (0–1 scale)
def normalize(series):
    return (series - series.min()) / (series.max() - series.min())

df_final['Norm_WC_Ratio'] = normalize(df_final['Working_Capital_Ratio'])
df_final['Norm_NTC'] = 1 - normalize(df_final['NTC'])  # inverse, lower NTC is better
df_final['Norm_Leverage'] = 1 - normalize(df_final['Leverage'])  # inverse, lower leverage is better
df_final['Norm_Cash_Ratio'] = normalize(df_final['Cash_Ratio'])

# Weighted average efficiency score
df_final['Efficiency_Index'] = (
    0.3 * df_final['Norm_WC_Ratio'] +
    0.3 * df_final['Norm_NTC'] +
    0.2 * df_final['Norm_Leverage'] +
    0.2 * df_final['Norm_Cash_Ratio']
)

# --- 6. Sector Ranking (if sector column available) ---
if 'sector' in df_final.columns:
    df_final['Sector_Rank'] = df_final.groupby('sector')['Efficiency_Index'].rank(ascending=False)

# --- Final Output ---
# print(df_final[['company','year','Working_Capital','Working_Capital_Ratio','NTC','ROE','Tobins_Q','Efficiency_Index']].head())

In [16]:
columnsh=df_final.columns[-25:]

In [17]:
columnsh

Index(['Loans Receivable', 'Interest Payable',
       'Dueto Related Parties Non Current', 'Dueto Related Parties Current',
       'Duefrom Related Parties Non Current',
       'Duefrom Related Parties Current', 'Working_Capital',
       'Working_Capital_Ratio', 'Cash_Ratio', 'Liquidity', 'Leverage', 'Size',
       'year', 'Revenue_Growth', 'Revenue_Growth_pct', 'Inventory_Days',
       'Receivable_Days', 'Payable_Days', 'NTC', 'Norm_WC_Ratio', 'Norm_NTC',
       'Norm_Leverage', 'Norm_Cash_Ratio', 'Efficiency_Index', 'Sector_Rank'],
      dtype='object', name='Unnamed: 0')

In [22]:
df_final[cols]

Unnamed: 0,Working_Capital_Ratio,Cash_Ratio,Leverage,Size,Revenue_Growth,NTC,Efficiency_Index
3,1.517603,0.08798,1.842482,25.400210,NaN,-22.412543,0.236581
2,0.92774,0.0952,2.172117,25.441056,0.102038,NaN,NaN
1,0.845525,0.060414,2.710693,25.741793,0.217934,NaN,NaN
0,1.206527,0.079333,1.560649,26.009951,0.313635,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
2271,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2270,1.564074,0.083909,0.248294,26.350721,NaN,181.434122,0.239424
2269,1.811055,0.088199,0.068218,26.274534,0.138269,167.211247,0.23994
2268,2.153054,0.077313,0.040556,26.402783,0.127013,174.018434,0.239692
2267,1.885297,0.091444,0.134145,26.642205,0.186752,154.771166,0.239914

In [23]:
df_final[['company','sector']]

Unnamed: 0    company              sector
3              360ONE  Financial Services
2              360ONE  Financial Services
1              360ONE  Financial Services
0              360ONE  Financial Services
8             3MINDIA                 NaN
...               ...                 ...
2271        ZYDUSLIFE          Healthcare
2270        ZYDUSLIFE          Healthcare
2269        ZYDUSLIFE          Healthcare
2268        ZYDUSLIFE          Healthcare
2267        ZYDUSLIFE          Healthcare

[2272 rows x 2 columns]

In [25]:
df_final1 = df_final.fillna(0)

C:\Users\ayush\AppData\Local\Temp\ipykernel_16940\2432747659.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_final1 = df_final.fillna(0)

In [45]:


cols = [
    "Working_Capital_Ratio",
    "Cash_Ratio",
    "Leverage",
    "Size",
    "Revenue_Growth",
    "NTC",
    "Efficiency_Index"
]

# Group by Company and Sector, then compute statistics
grouped_stats_2025 = (
    df_final1[df_final1['year']==2025].groupby(["sector"])[cols]
      .agg(['mean', 'median', 'std', 'min', 'max'])
)

grouped_stats_2024 = (
    df_final1[df_final1['year']==2024].groupby(["sector"])[cols]
      .agg(['mean', 'median', 'std', 'min', 'max'])
)

grouped_stats_2023 = (
    df_final1[df_final1['year']==2023].groupby(["sector"])[cols]
      .agg(['mean', 'median', 'std', 'min', 'max'])
)

grouped_stats_2022 = (
    df_final1[df_final1['year']==2022].groupby(["sector"])[cols]
      .agg(['mean', 'median', 'std', 'min', 'max'])
)

grouped_stats_2021 = (
    df_final1[df_final1['year']==2021].groupby(["sector"])[cols]
      .agg(['mean', 'median', 'std', 'min', 'max'])
)

In [52]:
grouped_stats_2025[['Working_Capital_Ratio','Cash_Ratio']]

Unnamed: 0             Working_Capital_Ratio                                 \
                                        mean    median        std       min
sector
Basic Materials                     1.974063  1.426066   2.108620  0.432558
Communication Services              2.290710  1.304635   2.687202  0.029575
Consumer Cyclical                   1.760026  1.423032   1.190306  0.425718
Consumer Defensive                  1.729556  1.520591   0.626219  0.796986
Energy                              1.645447  1.100351   1.337737  0.599358
Financial Services                  3.351489  0.000000  15.356047  0.000000
Healthcare                          2.577957  1.899317   1.632481  0.833891
Industrials                         2.576099  1.932438   1.794692  0.660106
Real Estate                         2.032280  1.590022   1.377652  1.138691
Technology                          2.503572  2.080786   1.391064  0.875214
Utilities                           1.126155  0.992495   0.603164  0.246993

Unnamed: 0                         Cash_Ratio                                \
                               max       mean    median       std       min
sector
Basic Materials          16.345804   0.111804  0.082098  0.104309  0.000711
Communication Services    9.343123   0.226913  0.082475  0.432097  0.002500
Consumer Cyclical         6.943325   0.173873  0.079014  0.291044  0.004398
Consumer Defensive        3.062156   0.118157  0.062421  0.142505  0.000139
Energy                    4.715747   0.154985  0.040293  0.283758  0.000825
Financial Services      110.443526   0.201385  0.000000  0.970998  0.000000
Healthcare                6.965043   0.261260  0.178907  0.273337  0.004914
Industrials              10.482037   0.284439  0.129956  0.443033  0.000476
Real Estate               5.429833   0.110534  0.066484  0.180936  0.006035
Technology                6.903988   0.283951  0.254660  0.269753  0.005229
Utilities                 2.865980   0.146912  0.079765  0.209152  0.007713

Unnamed: 0
                             max
sector
Basic Materials         0.398210
Communication Services  1.666273
Consumer Cyclical       1.906496
Consumer Defensive      0.523122
Energy                  1.051273
Financial Services      7.303459
Healthcare              1.633513
Industrials             2.913412
Real Estate             0.673148
Technology              1.229127
Utilities               0.948630

In [49]:
grouped_stats_2025['Cash_Ratio']

                            mean    median       std       min       max
sector
Basic Materials         0.111804  0.082098  0.104309  0.000711  0.398210
Communication Services  0.226913  0.082475  0.432097  0.002500  1.666273
Consumer Cyclical       0.173873  0.079014  0.291044  0.004398  1.906496
Consumer Defensive      0.118157  0.062421  0.142505  0.000139  0.523122
Energy                  0.154985  0.040293  0.283758  0.000825  1.051273
Financial Services      0.201385  0.000000  0.970998  0.000000  7.303459
Healthcare              0.261260  0.178907  0.273337  0.004914  1.633513
Industrials             0.284439  0.129956  0.443033  0.000476  2.913412
Real Estate             0.110534  0.066484  0.180936  0.006035  0.673148
Technology              0.283951  0.254660  0.269753  0.005229  1.229127
Utilities               0.146912  0.079765  0.209152  0.007713  0.948630

In [ ]:
print(grouped_stats_2025)

Unnamed: 0             Working_Capital_Ratio                                 \
                                        mean    median        std       min
sector
Basic Materials                     1.974063  1.426066   2.108620  0.432558
Communication Services              2.290710  1.304635   2.687202  0.029575
Consumer Cyclical                   1.760026  1.423032   1.190306  0.425718
Consumer Defensive                  1.729556  1.520591   0.626219  0.796986
Energy                              1.645447  1.100351   1.337737  0.599358
Financial Services                  3.351489  0.000000  15.356047  0.000000
Healthcare                          2.577957  1.899317   1.632481  0.833891
Industrials                         2.576099  1.932438   1.794692  0.660106
Real Estate                         2.032280  1.590022   1.377652  1.138691
Technology                          2.503572  2.080786   1.391064  0.875214
Utilities                           1.126155  0.992495   0.603164  0.246993

Unnamed: 0                         Cash_Ratio                                \
                               max       mean    median       std       min
sector
Basic Materials          16.345804   0.111804  0.082098  0.104309  0.000711
Communication Services    9.343123   0.226913  0.082475  0.432097  0.002500
Consumer Cyclical         6.943325   0.173873  0.079014  0.291044  0.004398
Consumer Defensive        3.062156   0.118157  0.062421  0.142505  0.000139
Energy                    4.715747   0.154985  0.040293  0.283758  0.000825
Financial Services      110.443526   0.201385  0.000000  0.970998  0.000000
Healthcare                6.965043   0.261260  0.178907  0.273337  0.004914
Industrials              10.482037   0.284439  0.129956  0.443033  0.000476
Real Estate               5.429833   0.110534  0.066484  0.180936  0.006035
Technology                6.903988   0.283951  0.254660  0.269753  0.005229
Utilities                 2.865980   0.146912  0.079765  0.209152  0.007713

Unnamed: 0                        ...          NTC                            \
                             max  ...         mean       median          std
sector                            ...
Basic Materials         0.398210  ...    67.165355    62.786840    78.898868
Communication Services  1.666273  ...    -6.251429     0.000000   175.583035
Consumer Cyclical       1.906496  ...    48.597399    32.505414    87.448738
Consumer Defensive      0.523122  ...    70.059471    39.676332   100.713544
Energy                  1.051273  ...    26.222998    21.127215    41.039778
Financial Services      7.303459  ...     0.000000     0.000000     0.000000
Healthcare              1.633513  ...   105.103146   126.445253   125.890444
Industrials             2.913412  ...   101.127861    56.091074   155.023934
Real Estate             0.673148  ...  2246.123839  1486.038735  2153.878767
Technology              1.229127  ...    35.091153    34.033340    51.306562
Utilities               0.948630  ...   -60.974109    -0.347849   327.167289

Unnamed: 0                                       Efficiency_Index            \
                                min          max             mean    median
sector
Basic Materials         -211.904613   359.622073         0.240082  0.239137
Communication Services  -226.398659   518.762980         0.137228  0.233048
Consumer Cyclical       -135.424979   294.295207         0.233820  0.239153
Consumer Defensive       -94.846685   273.409027         0.240530  0.238978
Energy                   -28.490816   131.716669         0.240711  0.237549
Financial Services         0.000000     0.000000         0.000000  0.000000
Healthcare              -137.118082   326.274312         0.235196  0.241344
Industrials             -116.148459   875.312539         0.239903  0.240699
Real Estate              300.752342  8097.546174         0.235684  0.235387
Technology               -15.008629   257.697120         0.152182  0.237975
Utilities              -1478.985282   332.767418         0.239657  0.238807

Unnamed: 0
                             std       min       max
sector
Basic Materials         0.003185  0.235190  0.248442
Communication Services  0.123397  0.000000  0.248030
Consumer Cyclical       0.043486  0.000000  0.290009
Consumer Defensive      0.004258  0.236057  0.252318
Energy                  0.007884  0.235096  0.264661
Financial Services      0.000000  0.000000  0.000000
Healthcare              0.047179  0.000000  0.282223
Industrials             0.037753  0.000000  0.317451
Real Estate             0.007359  0.224306  0.255687
Technology              0.120530  0.000000  0.271251
Utilities               0.006163  0.228088  0.261361

[11 rows x 35 columns]

: